const feeConfigurations=[
  {id:'FEE-RWA-001',domain:'RWA trading',rule:'Customer transaction fee',customer:'0.40%',cost:'0.20%',margin:'0.20%',scope:'All RWA products',basis:'Trade notional',status:'Active',tone:'good',effective:'01 Jun 2026',dependency:'Demo assumption'},
  {id:'FEE-FX-001',domain:'FX & Liquidity',rule:'AUDD conversion spread',customer:'30 bps',cost:'10 bps + 2 bps fee',margin:'≈17 bps net',scope:'AUDD/USDT · USDT/AUDD',basis:'Converted amount',status:'Active',tone:'good',effective:'01 Jun 2026',dependency:'Provider-dependent'},
  {id:'FEE-REM-001',domain:'Global Remittance',rule:'Same-name payout fee',customer:'1.00% + 5 AUDD',cost:'0.50%',margin:'0.50% + 5 AUDD',scope:'All enabled corridors',basis:'Send amount',status:'Active',tone:'good',effective:'01 Jun 2026',dependency:'Provider-dependent'},
  {id:'FEE-CARD-V',domain:'U-Card funding',rule:'Virtual Card funding',customer:'1.50%',cost:'0.20%',margin:'1.30%',scope:'Virtual Card',basis:'AUDD funded',status:'Active',tone:'good',effective:'01 Jun 2026',dependency:'Issuer-dependent'},
  {id:'FEE-CARD-G',domain:'U-Card funding',rule:'Gold Card funding',customer:'1.00%',cost:'0.20%',margin:'0.80%',scope:'Gold Card',basis:'AUDD funded',status:'Active',tone:'good',effective:'01 Jun 2026',dependency:'Issuer-dependent'},
  {id:'FEE-CARD-B',domain:'U-Card funding',rule:'Black Card funding',customer:'0.50%',cost:'0.20%',margin:'0.30%',scope:'Black Card',basis:'AUDD funded',status:'Active',tone:'good',effective:'01 Jun 2026',dependency:'Issuer-dependent'},
  {id:'FEE-CARD-FX',domain:'U-Card spending',rule:'International card FX markup',customer:'2.50%',cost:'1.80%',margin:'0.70%',scope:'Non-AUD card purchases',basis:'Settled card amount',status:'Proposed',tone:'neutral',effective:'Not scheduled',dependency:'Issuer-dependent'},
  {id:'FEE-CARD-INT',domain:'U-Card spending',rule:'Interchange revenue share',customer:'No direct charge',cost:'Issuer retains balance',margin:'0.35% indicative',scope:'Eligible settled purchases',basis:'Settled card amount',status:'Proposed',tone:'neutral',effective:'Not scheduled',dependency:'Partner-dependent'},
  {id:'FEE-AUDD-001',domain:'AUDD acquisition',rule:'Fiat gateway conversion spread',customer:'0.35%',cost:'0.12%',margin:'0.23%',scope:'Enabled fiat gateways',basis:'AUDD delivered',status:'Draft',tone:'warn',effective:'Not scheduled',dependency:'Proposed'},
  {id:'FEE-WALLET-001',domain:'External wallet',rule:'On-chain transfer fee',customer:'Network + 1 AUDD',cost:'Network fee',margin:'1 AUDD',scope:'Supported chains',basis:'Per transfer',status:'Draft',tone:'warn',effective:'Not scheduled',dependency:'Proposed'}
];

const cardPriceConfigurations=[
  {id:'CARD-PRICE-V',type:'Virtual Card',price:'1.00',currency:'USD',issuanceCost:'0.45 USD',saleMargin:'0.55 USD',funding:'1.50%',provider:'0.20%',display:'US$1',availability:'Global eligible markets',frontEnd:'Published',status:'Active',tone:'good',effective:'01 Jun 2026'},
  {id:'CARD-PRICE-G',type:'Gold Card',price:'99.00',currency:'AUDD',issuanceCost:'42 AUDD',saleMargin:'57 AUDD',funding:'1.00%',provider:'0.20%',display:'99 AUDD',availability:'Selected delivery markets',frontEnd:'Published',status:'Active',tone:'good',effective:'01 Jun 2026'},
  {id:'CARD-PRICE-B',type:'Black Card',price:'199.00',currency:'AUDD',issuanceCost:'78 AUDD',saleMargin:'121 AUDD',funding:'0.50%',provider:'0.20%',display:'199 AUDD',availability:'Eligible premium clients',frontEnd:'Published',status:'Active',tone:'good',effective:'01 Jun 2026'}
];

const configurationVersions=[
  {version:'CFG-2026.06.01',change:'Initial demo pricing set',scope:'RWA · FX · Remittance · U-Card',maker:'Product Admin',checker:'Finance Controller',effective:'01 Jun 2026 00:00 UTC',status:'Active',tone:'good'},
  {version:'CFG-2026.06.18-D1',change:'AUDD gateway and wallet fee proposal',scope:'AUDD · External wallet',maker:'Commercial Admin',checker:'Pending approval',effective:'Not scheduled',status:'Draft',tone:'warn'},
  {version:'CFG-2026.05.15',change:'U-Card launch price rehearsal',scope:'U-Card product prices',maker:'Card Operations',checker:'Finance Controller',effective:'Superseded 01 Jun 2026',status:'Archived',tone:'neutral'}
];

function configurationHead(){return `<div class="page-head"><div class="page-title"><small>${t('configuration')}</small><h1>${t('configTitle')}</h1><p>${t('configSub')}</p></div><div class="page-actions"><button class="btn" data-action="export-config">${L('Export configuration','导出配置')}</button><button class="btn primary" data-action="new-config-rule">＋ ${L('New pricing rule','新增费率规则')}</button></div></div>`}

function configurationPage(){
  return `${configurationHead()}<section class="metric-grid">${metric(L('Active fee rules','生效费率规则'),'6',L('2 draft rules await approval','2项草稿待审批'),'⚙')}${metric(L('Published card products','已发布卡产品'),'3',L('Prices visible in the customer app','售价已同步前端'),'▣','#7857d8','#f1edff')}${metric(L('Pending approvals','待审批变更'),'1',L('Maker-checker required','必须双人复核'),'!','#f5a524','#fff6e5')}${metric(L('Next scheduled change','下次计划生效'),'None',L('No approved future version','暂无已审批未来版本'),'◷','#17b58a','#eaf9f4')}</section><div class="section-tabs config-tabs"><button class="${state.configView==='fees'?'active':''}" data-config-view="fees">${L('Fee rules','费率规则')} <b>${feeConfigurations.length}</b></button><button class="${state.configView==='cards'?'active':''}" data-config-view="cards">${L('U-Card pricing','U卡售价')} <b>${cardPriceConfigurations.length}</b></button><button class="${state.configView==='versions'?'active':''}" data-config-view="versions">${L('Versions & approvals','版本与审批')} <b>${configurationVersions.length}</b></button></div>${state.configView==='fees'?feeRulesView():state.configView==='cards'?cardPricingView():configurationVersionsView()}`;
}

function feeRulesView(){return `<div class="config-callout"><b>${L('Pricing control','定价控制')}</b><span>${L('Customer fees, third-party costs and platform margin are stored separately. Changes create a new version and do not rewrite historical transactions.','用户费率、第三方成本和平台差价必须分别保存。修改后生成新版本，不改写历史交易。')}</span></div><div class="table-wrap"><table class="config-table"><thead><tr><th>${L('Rule ID','规则编号')}</th><th>${L('Business domain','业务模块')}</th><th>${L('Pricing rule','费率规则')}</th><th>${L('Customer charge','用户收费')}</th><th>${L('Provider cost','服务商成本')}</th><th>${L('Expected margin','预计差价')}</th><th>${L('Scope / basis','范围 / 计费基础')}</th><th>${L('Classification','配置属性')}</th><th>${L('Effective from','生效时间')}</th><th>${L('Status','状态')}</th><th>${t('actions')}</th></tr></thead><tbody>${feeConfigurations.map(x=>`<tr><td class="mono">${x.id}</td><td><strong>${x.domain}</strong></td><td>${x.rule}</td><td class="pricing-value">${x.customer}</td><td class="cost-cell">${x.cost}</td><td class="margin-cell">${x.margin}</td><td><strong class="cell-main">${x.scope}</strong><small class="cell-sub">${x.basis}</small></td><td><span class="dependency-chip">${x.dependency}</span></td><td>${x.effective}</td><td>${status(x.status,x.tone)}</td><td><button class="btn small" data-action="edit-config" data-kind="fee" data-config="${x.id}">${L('Edit','编辑')}</button></td></tr>`).join('')}</tbody></table></div>`}

function cardPricingView(){return `<div class="config-callout"><b>${L('Customer app sales configuration','用户端销售配置')}</b><span>${L('The published price and funding fee shown here control the U-Card acquisition cards in the customer app. Provider costs remain internal.','这里发布的售价和充值费率控制用户端的U卡销售页面；服务商成本只在后台展示。')}</span></div><div class="card-config-grid">${cardPriceConfigurations.map(x=>`<article class="card-config-card"><div class="card-config-visual ${x.type.toLowerCase().replaceAll(' ','-')}"><small>AUDC U-CARD</small><strong>${x.type}</strong><span>${x.display}</span></div><div class="card-config-body"><div class="config-row"><span>${L('Front-end sale price','前端销售价格')}</span><strong>${x.price} ${x.currency}</strong></div><div class="config-row"><span>${L('Issuer / production cost','发卡及制作成本')}</span><strong class="cost-cell">${x.issuanceCost}</strong></div><div class="config-row"><span>${L('Gross card-sale margin','售卡毛利')}</span><strong class="margin-cell">${x.saleMargin}</strong></div><div class="config-row"><span>${L('Customer funding fee','用户充值费率')}</span><strong>${x.funding}</strong></div><div class="config-row"><span>${L('Funding provider cost','充值服务商成本')}</span><strong>${x.provider}</strong></div><div class="config-row"><span>${L('Availability','销售范围')}</span><strong>${x.availability}</strong></div><div class="config-row"><span>${L('Front-end status','前端状态')}</span>${status(x.frontEnd,'good')}</div><footer><span>${L('Effective','生效')} ${x.effective}</span><button class="btn small" data-action="edit-config" data-kind="card" data-config="${x.id}">${L('Edit pricing','编辑定价')}</button></footer></div></article>`).join('')}</div>`}

function configurationVersionsView(){return `<div class="config-callout"><b>Maker-checker</b><span>${L('Price changes require an independent approver, a future effective timestamp and an immutable audit event. Emergency changes must record a reason and expiry.','价格变更需要独立审批人、未来生效时间和不可变审计事件。紧急变更还必须记录原因和失效时间。')}</span></div><div class="table-wrap"><table><thead><tr><th>${L('Version','版本')}</th><th>${L('Change summary','变更摘要')}</th><th>${L('Scope','影响范围')}</th><th>Maker</th><th>Checker</th><th>${L('Effective time','生效时间')}</th><th>${L('Status','状态')}</th><th>${t('actions')}</th></tr></thead><tbody>${configurationVersions.map(x=>`<tr><td class="mono">${x.version}</td><td>${x.change}</td><td>${x.scope}</td><td>${x.maker}</td><td>${x.checker}</td><td>${x.effective}</td><td>${status(x.status,x.tone)}</td><td><button class="btn small" data-action="view-config-version" data-config="${x.version}">${t('viewDetails')}</button></td></tr>`).join('')}</tbody></table></div>`}

function openNewConfigRule(){openDrawer(`<div class="drawer-head"><h2>${L('New pricing rule','新增费率规则')}</h2><button class="drawer-close" data-action="close-drawer">×</button></div><div class="drawer-body"><div class="notice"><b>!</b><span>${L('A new rule starts as a draft and requires an independent checker before its scheduled effective time.','新增规则初始为草稿，必须由独立审批人在计划生效前复核。')}</span></div><div class="form-stack"><label><span>${L('Business domain','业务模块')}</span><select><option>RWA trading</option><option>FX & Liquidity</option><option>Global Remittance</option><option>U-Card</option><option>AUDD acquisition</option><option>External wallet</option></select></label><label><span>${L('Rule name','规则名称')}</span><input placeholder="Customer fee / provider cost / margin"></label><label><span>${L('Customer charge','用户收费')}</span><input placeholder="0.00% or fixed amount"></label><label><span>${L('Provider cost','服务商成本')}</span><input placeholder="0.00% or fixed amount"></label><label><span>${L('Scope','适用范围')}</span><input placeholder="Countries, products, member groups"></label><label><span>${L('Effective time','计划生效时间')}</span><input type="datetime-local" value="2026-06-23T00:00"></label><label><span>${L('Change reason','变更原因')}</span><textarea>New commercial pricing rule</textarea></label></div><div class="drawer-actions"><button class="btn primary" data-action="save-demo-record">${L('Submit draft for approval','提交草稿审批')}</button><button class="btn" data-action="close-drawer">${t('close')}</button></div></div>`)}

function openConfigEditor(kind,id){
  const x=kind==='card'?cardPriceConfigurations.find(v=>v.id===id):feeConfigurations.find(v=>v.id===id);if(!x)return;
  openDrawer(`<div class="drawer-head"><div><small class="mono">${x.id}</small><h2>${kind==='card'?L('Edit U-Card pricing','编辑U卡定价'):L('Edit pricing rule','编辑费率规则')}</h2></div><button class="drawer-close" data-action="close-drawer">×</button></div><div class="drawer-body"><div class="notice"><b>!</b><span>${L('Saving creates a draft version. A different authorised operator must approve it before it can affect customer quotes.','保存后仅生成草稿版本，必须由另一名授权人员审批后才会影响用户报价。')}</span></div><div class="form-stack">${kind==='card'?`<label><span>${L('Product','产品')}</span><input value="${x.type}" disabled></label><label><span>${L('Sales price','销售价格')}</span><input value="${x.price}"></label><label><span>${L('Price currency','计价币种')}</span><select><option ${x.currency==='AUDD'?'selected':''}>AUDD</option><option ${x.currency==='USD'?'selected':''}>USD</option></select></label><label><span>${L('Customer funding fee','用户充值费率')}</span><input value="${x.funding}"></label><label><span>${L('Front-end availability','前端销售状态')}</span><select><option>Published</option><option>Hidden</option><option>Waitlist</option></select></label>`:`<label><span>${L('Business domain','业务模块')}</span><input value="${x.domain}" disabled></label><label><span>${L('Customer charge','用户收费')}</span><input value="${x.customer}"></label><label><span>${L('Provider cost','服务商成本')}</span><input value="${x.cost}"></label><label><span>${L('Scope','适用范围')}</span><input value="${x.scope}"></label>`}<label><span>${L('Effective time','计划生效时间')}</span><input type="datetime-local" value="2026-06-23T00:00"></label><label><span>${L('Change reason','变更原因')}</span><textarea>Commercial pricing review</textarea></label></div><div class="drawer-actions"><button class="btn primary" data-action="save-demo-record">${L('Submit draft for approval','提交草稿审批')}</button><button class="btn" data-action="close-drawer">${t('close')}</button></div></div>`);
}

function openConfigurationVersion(id){const x=configurationVersions.find(v=>v.version===id);if(!x)return;openDrawer(`<div class="drawer-head"><div><small class="mono">${x.version}</small><h2>${L('Configuration version','配置版本')}</h2></div><button class="drawer-close" data-action="close-drawer">×</button></div><div class="drawer-body"><section class="order-hero"><div><span>${L('Change summary','变更摘要')}</span><strong style="font-size:18px">${x.change}</strong><small>${x.scope}</small></div>${status(x.status,x.tone)}</section><section class="detail-section"><h3>${L('Approval control','审批控制')}</h3><div class="detail-grid"><div class="detail"><span>Maker</span><strong>${x.maker}</strong></div><div class="detail"><span>Checker</span><strong>${x.checker}</strong></div><div class="detail"><span>${L('Effective time','生效时间')}</span><strong>${x.effective}</strong></div><div class="detail"><span>${L('Historical transactions','历史交易')}</span><strong>${L('Unaffected','不受影响')}</strong></div></div></section><section class="detail-section"><h3>${L('Audit events','审计事件')}</h3><div class="timeline"><div class="timeline-item"><strong>${L('Draft created','草稿已创建')}</strong><small>${x.maker}</small></div><div class="timeline-item"><strong>${L('Independent review','独立复核')}</strong><small>${x.checker}</small></div><div class="timeline-item"><strong>${L('Configuration snapshot retained','配置快照已保留')}</strong><small>${L('Immutable version reference','不可变版本编号')}</small></div></div></section><div class="drawer-actions"><button class="btn" data-action="close-drawer">${t('close')}</button></div></div>`)}
