const reconciliationStatements = [
  {id:'GL-20260619-D',level:'Master',category:'All businesses',cycle:'Daily',from:'2026-06-19',to:'2026-06-19',opening:5841200,inflow:428650,outflow:391420,closing:5878430,external:5877565.80,difference:864.20,status:'Mismatch',statusClass:'bad'},
  {id:'GL-2026-W25',level:'Master',category:'All businesses',cycle:'Weekly',from:'2026-06-15',to:'2026-06-21',opening:5520840,inflow:1640320,outflow:1282730,closing:5878430,external:5878110,difference:320,status:'Review',statusClass:'warn'},
  {id:'GL-202606',level:'Master',category:'All businesses',cycle:'Monthly',from:'2026-06-01',to:'2026-06-30',opening:4930100,inflow:4812450,outflow:3864120,closing:5878430,external:5878430,difference:0,status:'In progress',statusClass:'info'},
  {id:'SL-RWA-0619',level:'Sub-ledger',category:'RWA',cycle:'Daily',from:'2026-06-19',to:'2026-06-19',opening:861240,inflow:144580,outflow:98620,closing:907200,external:906335.80,difference:864.20,status:'Mismatch',statusClass:'bad'},
  {id:'SL-FX-0619',level:'Sub-ledger',category:'FX & Liquidity',cycle:'Daily',from:'2026-06-19',to:'2026-06-19',opening:412800,inflow:51840,outflow:49720,closing:414920,external:414920,difference:0,status:'Matched',statusClass:'good'},
  {id:'SL-REM-0619',level:'Sub-ledger',category:'Global Remittance',cycle:'Daily',from:'2026-06-19',to:'2026-06-19',opening:208440,inflow:33680,outflow:28930,closing:213190,external:213190,difference:0,status:'Matched',statusClass:'good'},
  {id:'SL-CARD-0619',level:'Sub-ledger',category:'U-Card',cycle:'Daily',from:'2026-06-19',to:'2026-06-19',opening:516300,inflow:12040,outflow:11540,closing:516800,external:516701,difference:99,status:'Review',statusClass:'warn'},
  {id:'SL-AUDD-0619',level:'Sub-ledger',category:'AUDD & Custody',cycle:'Daily',from:'2026-06-19',to:'2026-06-19',opening:3842420,inflow:186510,outflow:202610,closing:3826320,external:3826000,difference:320,status:'Timing difference',statusClass:'warn'}
];

const reconciliationBreaks = [
  {id:'REC-19062',statement:'SL-RWA-0619',category:'RWA',reference:'ORD-71142',platform:10000,partner:9135.80,difference:864.20,reason:'Partner settlement callback missing',owner:'RWA Operations',age:'2h 18m',status:'Open',statusClass:'bad'},
  {id:'REC-19059',statement:'SL-AUDD-0619',category:'AUDD & Custody',reference:'TRF-99218',platform:18400,partner:18080,difference:320,reason:'Custody posting cut-off difference',owner:'Treasury',age:'1h 42m',status:'Investigating',statusClass:'warn'},
  {id:'REC-19051',statement:'SL-CARD-0619',category:'U-Card',reference:'ACT-10492',platform:99,partner:0,difference:99,reason:'Issuer activation fee not yet invoiced',owner:'Card Operations',age:'48m',status:'Review',statusClass:'warn'},
  {id:'REC-19044',statement:'SL-FX-0619',category:'FX & Liquidity',reference:'FX-880142',platform:10020.06,partner:10020.06,difference:0,reason:'Evidence received and matched',owner:'Finance',age:'Closed',status:'Resolved',statusClass:'good'}
];

function reconFilterPanel(){
  const f=state.reconFilters;
  return `<section class="filter-panel"><div class="filter-title"><div><strong>${L('Statement filters','账单筛选')}</strong><small>${L('Filter by accounting date, cycle, business ledger and status','按会计日期、对账周期、业务分账和状态筛选')}</small></div><button class="text-link" data-action="reset-recon-filters">${t('resetFilters')}</button></div><div class="recon-filter-grid"><label><span>${L('From date','开始日期')}</span><input type="date" id="reconFrom" value="${f.from}"></label><label><span>${L('To date','结束日期')}</span><input type="date" id="reconTo" value="${f.to}"></label><label><span>${L('Reconciliation cycle','对账周期')}</span><select id="reconCycle"><option value="">${t('all')}</option>${['Daily','Weekly','Monthly'].map(x=>`<option ${f.cycle===x?'selected':''}>${x}</option>`).join('')}</select></label><label><span>${L('Business ledger','业务分类')}</span><select id="reconCategory"><option value="">${t('all')}</option>${['RWA','FX & Liquidity','Global Remittance','U-Card','AUDD & Custody'].map(x=>`<option ${f.category===x?'selected':''}>${x}</option>`).join('')}</select></label><label><span>${L('Status','对账状态')}</span><select id="reconStatus"><option value="">${t('all')}</option>${['Matched','Mismatch','Review','Timing difference','In progress','Open','Investigating','Resolved'].map(x=>`<option ${f.status===x?'selected':''}>${x}</option>`).join('')}</select></label><button class="btn primary filter-submit" data-action="apply-recon-filters">${t('applyFilters')}</button></div></section>`;
}

function filteredReconStatements(){
  const f=state.reconFilters;
  return reconciliationStatements.filter(x=>(state.reconView==='master'?x.level==='Master':x.level==='Sub-ledger')&&(!f.from||x.to>=f.from)&&(!f.to||x.from<=f.to)&&(!f.cycle||x.cycle===f.cycle)&&(!f.category||x.category===f.category)&&(!f.status||x.status===f.status));
}

function reconciliationPage(){
  return `${pageHead()}<section class="metric-grid">${metric(L('General ledger closing','总账期末余额'),'A$ 5.878M',L('Platform double-entry ledger','平台双重记账总账'),'Σ')}${metric(L('Business sub-ledgers','业务分账单'),'5',L('AUDD, RWA, FX, remittance, card','AUDD、RWA、FX、速汇、U卡'),'▤','#7857d8','#f1edff')}${metric(L('Unresolved difference','未解决差异'),'A$ 1,283.20',L('3 open reconciliation breaks','3笔待处理差异'),'!','#e45c64','#fff0f1')}${metric(L('Matched today','今日匹配率'),'99.98%',L('By transaction value','按交易金额计算'),'✓','#17b58a','#eaf9f4')}</section><div class="section-tabs recon-tabs"><button class="${state.reconView==='master'?'active':''}" data-recon-view="master">${L('General statements','总账单')} <b>3</b></button><button class="${state.reconView==='subledger'?'active':''}" data-recon-view="subledger">${L('Business sub-statements','业务分账单')} <b>5</b></button><button class="${state.reconView==='breaks'?'active':''}" data-recon-view="breaks">${L('Reconciliation breaks','对账差异')} <b>3</b></button></div>${state.reconView==='breaks'?reconciliationBreaksView():`${reconFilterPanel()}${reconciliationStatementTable(filteredReconStatements())}`}`;
}

function reconciliationStatementTable(rows){
  return `<div class="table-wrap"><table class="recon-table"><thead><tr><th>${L('Statement ID','账单编号')}</th><th>${L('Level / business','层级 / 业务')}</th><th>${L('Cycle','周期')}</th><th>${L('Accounting period','会计期间')}</th><th>${L('Opening balance','期初余额')}</th><th>${L('Inflows','本期流入')}</th><th>${L('Outflows','本期流出')}</th><th>${L('Closing balance','期末余额')}</th><th>${L('External statement','外部账单')}</th><th>${L('Difference','差异')}</th><th>${L('Status','状态')}</th><th>${t('actions')}</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td class="mono">${x.id}</td><td><strong class="cell-main">${x.category}</strong><small class="cell-sub">${x.level}</small></td><td>${x.cycle}</td><td>${x.from} → ${x.to}</td><td>${money(x.opening,'AUD')}</td><td class="amount positive">+${money(x.inflow,'AUD')}</td><td class="amount negative">-${money(x.outflow,'AUD')}</td><td><strong>${money(x.closing,'AUD')}</strong></td><td>${money(x.external,'AUD')}</td><td class="${x.difference?'cost-cell':'margin-cell'}">${money(x.difference,'AUD')}</td><td>${status(x.status,x.statusClass)}</td><td><button class="btn small" data-action="view-recon" data-recon="${x.id}">${t('viewDetails')}</button></td></tr>`).join(''):`<tr><td colspan="12"><div class="table-empty">${L('No statements match these filters','没有符合筛选条件的账单')}</div></td></tr>`}</tbody></table></div>`;
}

function reconciliationBreaksView(){
  const f=state.reconFilters;const rows=reconciliationBreaks.filter(x=>{const s=reconciliationStatements.find(v=>v.id===x.statement);return (!f.from||s.to>=f.from)&&(!f.to||s.from<=f.to)&&(!f.cycle||s.cycle===f.cycle)&&(!f.category||x.category===f.category)&&(!f.status||x.status===f.status)});
  return `${reconFilterPanel()}<div class="table-wrap"><table class="recon-table"><thead><tr><th>${L('Break ID','差异编号')}</th><th>${L('Sub-statement','分账单')}</th><th>${L('Business','业务')}</th><th>${L('Transaction reference','交易编号')}</th><th>${L('Platform ledger','平台账')}</th><th>${L('Partner statement','合作方账')}</th><th>${L('Difference','差异')}</th><th>${L('Reason','原因')}</th><th>${L('Owner / age','负责人 / 时长')}</th><th>${L('Status','状态')}</th><th>${t('actions')}</th></tr></thead><tbody>${rows.length?rows.map(x=>`<tr><td class="mono">${x.id}</td><td class="mono">${x.statement}</td><td>${x.category}</td><td class="mono">${x.reference}</td><td>${money(x.platform,'AUD')}</td><td>${money(x.partner,'AUD')}</td><td class="${x.difference?'cost-cell':'margin-cell'}">${money(x.difference,'AUD')}</td><td>${x.reason}</td><td><strong class="cell-main">${x.owner}</strong><small class="cell-sub">${x.age}</small></td><td>${status(x.status,x.statusClass)}</td><td><button class="btn small" data-action="view-recon" data-recon="${x.id}">${t('viewDetails')}</button></td></tr>`).join(''):`<tr><td colspan="11"><div class="table-empty">${L('No reconciliation breaks match these filters','没有符合筛选条件的对账差异')}</div></td></tr>`}</tbody></table></div>`;
}

function openReconRecord(id){
  const x=reconciliationStatements.find(v=>v.id===id)||reconciliationBreaks.find(v=>v.id===id);if(!x)return;const isBreak=!!x.statement;
  openDrawer(`<div class="drawer-head"><div><small class="mono">${x.id}</small><h2>${isBreak?L('Reconciliation break','对账差异'):L('Statement detail','账单详情')}</h2></div><button class="drawer-close" data-action="close-drawer">×</button></div><div class="drawer-body"><section class="order-hero"><div><span>${isBreak?L('Unresolved difference','未解决差异'):L('Closing balance','期末余额')}</span><strong>${money(isBreak?x.difference:x.closing,'AUD')}</strong><small>${isBreak?x.category:`${x.cycle} · ${x.from} → ${x.to}`}</small></div>${status(x.status,x.statusClass)}</section><section class="detail-section"><h3>${L('Reconciliation evidence','对账证据')}</h3><div class="detail-grid">${isBreak?`<div class="detail"><span>${L('Platform ledger','平台账')}</span><strong>${money(x.platform,'AUD')}</strong></div><div class="detail"><span>${L('Partner statement','合作方账')}</span><strong>${money(x.partner,'AUD')}</strong></div><div class="detail"><span>${L('Transaction reference','交易编号')}</span><strong class="mono">${x.reference}</strong></div><div class="detail"><span>${L('Owner','负责人')}</span><strong>${x.owner}</strong></div>`:`<div class="detail"><span>${L('Opening balance','期初余额')}</span><strong>${money(x.opening,'AUD')}</strong></div><div class="detail"><span>${L('Closing balance','期末余额')}</span><strong>${money(x.closing,'AUD')}</strong></div><div class="detail"><span>${L('External statement','外部账单')}</span><strong>${money(x.external,'AUD')}</strong></div><div class="detail"><span>${L('Difference','差异')}</span><strong>${money(x.difference,'AUD')}</strong></div>`}</div></section><section class="detail-section"><h3>${L('Audit trail','审计轨迹')}</h3><div class="timeline"><div class="timeline-item"><strong>${L('Platform ledger snapshot locked','平台账快照已锁定')}</strong><small>${L('Immutable period reference retained','保留不可变期间编号')}</small></div><div class="timeline-item"><strong>${L('Partner statement imported','合作方账单已导入')}</strong><small>${L('Source file hash and import operator recorded','已记录源文件哈希和导入人员')}</small></div><div class="timeline-item"><strong>${isBreak?x.reason:L('Automated matching completed','自动匹配已完成')}</strong><small>${L('Manual action remains fully audited','人工操作均保留审计记录')}</small></div></div></section><div class="drawer-actions"><button class="btn primary" data-action="resolve">${isBreak?t('investigate'):L('Approve statement','确认账单')}</button><button class="btn" data-action="close-drawer">${t('close')}</button></div></div>`);
}
